
package mis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class examInfo extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    public examInfo(Connection con) {
        initComponents();
        
        setSize(1290,700);
        this.con=con;
        updateTable();
    }
    
    private void updateTable()
    {
        try {
            String statement="select * from exam_info";
            
            ps=con.prepareStatement(statement);
            rs=ps.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        room = new javax.swing.JTextField();
        Class = new javax.swing.JTextField();
        participants = new javax.swing.JTextField();
        marks = new javax.swing.JTextField();
        teacher = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exam Page");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 204, 0))); // NOI18N
        jPanel1.setLayout(null);

        room.setPreferredSize(new java.awt.Dimension(10, 25));
        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        jPanel1.add(room);
        room.setBounds(126, 202, 105, 25);

        Class.setPreferredSize(new java.awt.Dimension(10, 25));
        Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassActionPerformed(evt);
            }
        });
        jPanel1.add(Class);
        Class.setBounds(126, 171, 105, 25);

        participants.setPreferredSize(new java.awt.Dimension(10, 25));
        participants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsActionPerformed(evt);
            }
        });
        jPanel1.add(participants);
        participants.setBounds(126, 140, 105, 25);

        marks.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel1.add(marks);
        marks.setBounds(126, 109, 105, 25);

        teacher.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel1.add(teacher);
        teacher.setBounds(126, 233, 105, 25);

        date.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel1.add(date);
        date.setBounds(126, 78, 105, 25);

        id.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel1.add(id);
        id.setBounds(126, 47, 105, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(26, 47, 33, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(26, 78, 33, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Marks");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(27, 109, 81, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Participants");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(27, 140, 81, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Class");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(27, 171, 81, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Room No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(27, 202, 81, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Teacher");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(27, 233, 81, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(77, 114, 300, 310);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(102, 51, 255))); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(51, 51, 255));
        save.setText("Save");
        save.setPreferredSize(new java.awt.Dimension(80, 30));
        save.setRolloverEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Delete");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(400, 220, 150, 195);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Database", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24), new java.awt.Color(0, 204, 153))); // NOI18N

        Table.setAutoCreateRowSorter(true);
        Table.setBackground(new java.awt.Color(0, 0, 0));
        Table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Table.setForeground(new java.awt.Color(51, 255, 51));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Table.setFocusable(false);
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setMinimumSize(new java.awt.Dimension(70, 130));
        Table.setName(""); // NOI18N
        Table.setRowHeight(30);
        Table.setRowMargin(2);
        Table.setSurrendersFocusOnKeystroke(true);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(651, 59, 560, 450);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        search.setToolTipText("Search Here");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mis/resource/search.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(80, 440, 300, 93);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 153));
        jButton3.setText("Show Full Database");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 540, 180, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mis/resource/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1290, 650);

        jMenu1.setText("Help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomActionPerformed

    private void participantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantsActionPerformed

    private void ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to update?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
            try {
                // TODO add your handling code here:

                String sql="update exam_info set Date='"+date.getText()+"',Marks="+marks.getText()+
                        ",Participants="+participants.getText()+",Class="+
                        Class.getText()+",Room="+room.getText()+",Teacher='"+teacher.getText()+
                        "' where Id="+id.getText()+"";
                
                ps=con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "updated!");
                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (id.getText()=="")
        {
            JOptionPane.showMessageDialog(null, "Empty data!");
        }
        else
        {
            try {
                // TODO add your handling code here:

                String sql="Insert into exam_info (Id,Date,Marks,Participants,Class,Room,Teacher) values (?,?,?,?,?,?,?)";
                ps=con.prepareStatement(sql);
                ps.setString(1,id.getText());
                ps.setString(2,date.getText());
                ps.setString(3,marks.getText());
                ps.setString(4,participants.getText());
                ps.setString(5,Class.getText());
                ps.setString(6,room.getText());
                ps.setString(7,teacher.getText());
                //rs=ps.executeQuery();
                ps.execute();
                JOptionPane.showMessageDialog(null, "Saved!!");
                updateTable();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to DELETE?","Delete",JOptionPane.YES_NO_OPTION);

        if (p==0)
        {
            try {
                // TODO add your handling code here:
                String ii=id.getText();
                String sql="delete from exam_info where Id="+ii+"";
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();

                JOptionPane.showMessageDialog(null, "Deleted!!");

                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to DELETE?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
            try {
                // TODO add your handling code here:
                String ii=id.getText();
                System.out.println(ii);
                String sql="delete from exam_info where Id="+ii+"";

                ps=con.prepareStatement(sql);
                // ps.setString(1,ii);
                ps.execute();

                JOptionPane.showMessageDialog(null, "Deleted!!");
                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        try {
            // TODO add your handling code here:

            int row=Table.getSelectedRow();
            if (row!=-1)
            {

                System.out.println(row);
                int ii=Table.convertRowIndexToModel(row);
                String str=(String) Table.getModel().getValueAt(ii, 0).toString();
                String sql="select * from exam_info where Id="+str+"";

                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();

                if (rs.next())
                {
                    id.setText(rs.getString("Id"));
                    date.setText(rs.getString("Date"));
                    marks.setText(rs.getString("Marks"));
                    participants.setText(rs.getString("Participants"));
                    Class.setText(rs.getString("Class"));
                    room.setText(rs.getString("Room"));
                    teacher.setText(rs.getString("Teacher"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_TableMouseClicked

    private void TableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TableMouseEntered

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        homePage.examPage=null;
    }//GEN-LAST:event_formWindowClosed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"First Select The row in the table .Then..\n"
                + "To update, edit the date in the respective field and click update\n"
                + "To save, Give a unique id number and click save\n"
                + "To delete, click delete "
                + "Also you can sort the data by clicking the respective column");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            // TODO add your handling code here:
            String sql="Select * from exam_info where Date LIKE ? OR Marks LIKE ? OR Participants LIKE ? OR Class LIKE ? OR Room LIKE ? OR Teacher LIKE ?";
                    
            String str=search.getText();
            ps=con.prepareStatement(sql);
            ps.setString(1,"%"+str+"%");
            ps.setString(2,"%"+str+"%");
            ps.setString(3,"%"+str+"%");
             ps.setString(4,"%"+str+"%");
              ps.setString(5,"%"+str+"%");
               ps.setString(6,"%"+str+"%");
            rs=ps.executeQuery();

            id.setText("");
            date.setText("");
            marks.setText("");
            participants.setText("");
            Class.setText("");
            room.setText("");
            teacher.setText("");
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_jButton3MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Class;
    private javax.swing.JTable Table;
    private javax.swing.JTextField date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField participants;
    private javax.swing.JTextField room;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JTextField teacher;
    // End of variables declaration//GEN-END:variables
}
