/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mis;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class teacherInfo extends javax.swing.JFrame {

    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    public teacherInfo(Connection con) {
        initComponents();
        setSize(1290,680);
       this.con=con;
        updateTable();
    }
        
    private void updateTable()
    {
        try {
            String statement="select * from teacher_info";
            
            ps=con.prepareStatement(statement);
            rs=ps.executeQuery();
            Table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        joined = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        post = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Page");
        setPreferredSize(new java.awt.Dimension(1920, 1200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(102, 153, 0))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 320));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 320));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(47, 97, 40, 17);

        id.setPreferredSize(new java.awt.Dimension(10, 30));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id);
        id.setBounds(125, 59, 128, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Joined");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(47, 170, 45, 17);

        age.setPreferredSize(new java.awt.Dimension(10, 30));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel2.add(age);
        age.setBounds(125, 132, 128, 30);

        name.setPreferredSize(new java.awt.Dimension(10, 30));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(125, 94, 128, 30);

        joined.setPreferredSize(new java.awt.Dimension(10, 30));
        jPanel2.add(joined);
        joined.setBounds(125, 170, 128, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Age");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(47, 135, 27, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Id");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(47, 59, 16, 17);

        post.setPreferredSize(new java.awt.Dimension(10, 30));
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        jPanel2.add(post);
        post.setBounds(125, 208, 128, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Post");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(47, 208, 31, 17);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(230, 276, 0, 0);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(90, 100, 320, 320);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Database", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24), new java.awt.Color(0, 204, 153))); // NOI18N

        Table.setAutoCreateRowSorter(true);
        Table.setBackground(new java.awt.Color(0, 0, 0));
        Table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Table.setForeground(new java.awt.Color(51, 255, 51));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Table.setFocusable(false);
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setSurrendersFocusOnKeystroke(true);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel4.add(jScrollPane1);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(725, 59, 486, 450);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(102, 51, 255))); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(51, 51, 255));
        save.setText("Save");
        save.setPreferredSize(new java.awt.Dimension(80, 30));
        save.setRolloverEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Delete");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.setRolloverEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 220, 150, 195);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        search.setToolTipText("Search Here");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mis/resource/search.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(90, 430, 324, 93);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 153));
        jButton3.setText("Show Full Database");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(830, 550, 180, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mis/resource/back.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 0, 1310, 720);

        jMenu1.setText("Help");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        try {
            // TODO add your handling code here:

            int row=Table.getSelectedRow();
            if (row!=-1)
            {

                System.out.println(row);
                int ii=Table.convertRowIndexToModel(row);
                String str=(String) Table.getModel().getValueAt(ii, 0).toString();
                String sql="select * from teacher_info where Id="+str+"";

                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();

                if (rs.next())
                {
                    id.setText(rs.getString("Id"));
                    name.setText(rs.getString("Name"));
                    age.setText(rs.getString("Age"));
                    joined.setText(rs.getString("Joined"));
                    post.setText(rs.getString("Post"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally{
            try {
                rs.close();
                ps.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_TableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to update?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
            try {
                // TODO add your handling code here:

                String sql="update teacher_info set Name='"+name.getText()+"',Age="+age.getText()+",Joined='"+joined.getText()+"',Post='"+post.getText()+"' where Id="+id.getText()+"";
                ps=con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "updated!");
                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (id.getText()=="")
        {
            JOptionPane.showMessageDialog(null, "Empty data!");
        }
        else
        {
            try {
                // TODO add your handling code here:

                String sql="Insert into teacher_info (Id,Name,Age,Joined,Post) values (?,?,?,?,?)";
                ps=con.prepareStatement(sql);
                ps.setString(1,id.getText());
                ps.setString(2,name.getText());
                ps.setString(3,age.getText());
                ps.setString(4,joined.getText());
                ps.setString(5,post.getText());

                //rs=ps.executeQuery();
                ps.execute();
                JOptionPane.showMessageDialog(null, "Saved!!");
                updateTable();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to DELETE?","Delete",JOptionPane.YES_NO_OPTION);

        if (p==0)
        {
            try {
                // TODO add your handling code here:
                String ii=id.getText();
                String sql="delete from teacher_info where Id="+ii+"";
                ps=con.prepareStatement(sql);
                rs=ps.executeQuery();

                JOptionPane.showMessageDialog(null, "Deleted!!");

                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Do you really want to DELETE?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0)
        {
            try {
                // TODO add your handling code here:
                String ii=id.getText();
                System.out.println(ii);
                String sql="delete from teacher_info where Id="+ii+"";

                ps=con.prepareStatement(sql);
                // ps.setString(1,ii);
                ps.execute();

                JOptionPane.showMessageDialog(null, "Deleted!!");
                updateTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally{
                try {
                    rs.close();
                    ps.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        homePage.teacherPage=null;
    }//GEN-LAST:event_formWindowClosing

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"First Select The row in the table .Then..\n"
                + "To update, edit the date in the respective field and click update\n"
                + "To save, Give a unique id number and click save\n"
                + "To delete, click delete "
                + "Also you can sort the data by clicking the respective column");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {
            // TODO add your handling code here:
            String sql="Select * from teacher_info where Name LIKE ? OR Age LIKE ? OR Joined LIKE ? OR Post LIKE ?";
            String str=search.getText();
            ps=con.prepareStatement(sql);
            ps.setString(1,"%"+str+"%");
            ps.setString(2,"%"+str+"%");
            ps.setString(3,"%"+str+"%");
            ps.setString(4,"%"+str+"%");
            rs=ps.executeQuery();

            id.setText("");
            name.setText("");
            age.setText("");
            joined.setText("");
            post.setText("");
            Table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_jButton3MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField age;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField joined;
    private javax.swing.JTextField name;
    private javax.swing.JTextField post;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
